pipeline {
    agent any

    environment {
        IMAGE_NAME = "flask-devops-app"
        CONTAINER_NAME = "flask-app"
        APP_PORT = "5000"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Cloning GitHub repository...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image from app folder...'
                sh '''
                    cd app
                    docker build -t $IMAGE_NAME:latest .
                '''
            }
        }

        stage('Stop Old Container') {
            steps {
                echo 'Stopping old container if exists...'
                sh '''
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                echo 'Running new Flask container...'
                sh '''
                    docker run -d \
                    --name $CONTAINER_NAME \
                    -p $APP_PORT:$APP_PORT \
                    $IMAGE_NAME:latest
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                echo 'Testing application...'
                sh '''
                    sleep 5
                    curl -f http://localhost:$APP_PORT
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully!'
        }

        failure {
            echo '❌ Pipeline failed. Check Jenkins logs.'
        }
    }
}
